#![allow(dead_code)]

use serde_json::Value;
use std::io::Write;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExportFormat {
    Csv,
    Json,
    Sql,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImportFormat {
    Csv,
    Json,
    Sql,
    MySqlDump,
}

impl ImportFormat {
    pub fn extension(&self) -> &'static str {
        match self {
            ImportFormat::Csv => "csv",
            ImportFormat::Json => "json",
            ImportFormat::Sql => "sql",
            ImportFormat::MySqlDump => "sql",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            ImportFormat::Csv => "CSV - First row as column headers",
            ImportFormat::Json => "JSON - Array of objects",
            ImportFormat::Sql => "SQL - Execute statements directly",
            ImportFormat::MySqlDump => "MySQL Dump - Convert to SQLite",
        }
    }

    pub fn all() -> &'static [ImportFormat] {
        &[
            ImportFormat::Csv,
            ImportFormat::Json,
            ImportFormat::Sql,
            ImportFormat::MySqlDump,
        ]
    }
}

/// Conflict resolution strategy for imports
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConflictStrategy {
    Fail,    // Abort on duplicate
    Replace, // UPDATE existing rows (INSERT OR REPLACE)
    Skip,    // Ignore duplicates (INSERT OR IGNORE)
}

impl ConflictStrategy {
    pub fn description(&self) -> &'static str {
        match self {
            ConflictStrategy::Fail => "Fail on conflict",
            ConflictStrategy::Replace => "Replace existing rows",
            ConflictStrategy::Skip => "Skip duplicates",
        }
    }

    pub fn sql_keyword(&self) -> &'static str {
        match self {
            ConflictStrategy::Fail => "INSERT INTO",
            ConflictStrategy::Replace => "INSERT OR REPLACE INTO",
            ConflictStrategy::Skip => "INSERT OR IGNORE INTO",
        }
    }
}

impl ExportFormat {
    pub fn extension(&self) -> &'static str {
        match self {
            ExportFormat::Csv => "csv",
            ExportFormat::Json => "json",
            ExportFormat::Sql => "sql",
        }
    }

    pub fn description(&self) -> &'static str {
        match self {
            ExportFormat::Csv => "CSV (Comma Separated Values)",
            ExportFormat::Json => "JSON (JavaScript Object Notation)",
            ExportFormat::Sql => "SQL (INSERT statements)",
        }
    }
}

/// Export table data to CSV format
pub fn export_to_csv(columns: &[String], rows: &[Vec<Value>]) -> String {
    let mut output = String::new();

    // Header row
    output.push_str(&columns.iter()
        .map(|c| escape_csv_field(c))
        .collect::<Vec<_>>()
        .join(","));
    output.push('\n');

    // Data rows
    for row in rows {
        let line: Vec<String> = row.iter()
            .map(|v| escape_csv_field(&value_to_string(v)))
            .collect();
        output.push_str(&line.join(","));
        output.push('\n');
    }

    output
}

/// Export table data to JSON format
pub fn export_to_json(columns: &[String], rows: &[Vec<Value>]) -> String {
    let records: Vec<serde_json::Map<String, Value>> = rows.iter()
        .map(|row| {
            columns.iter()
                .zip(row.iter())
                .map(|(col, val)| (col.clone(), val.clone()))
                .collect()
        })
        .collect();

    serde_json::to_string_pretty(&records).unwrap_or_else(|_| "[]".to_string())
}

/// Export table data to SQL INSERT statements
pub fn export_to_sql(table_name: &str, columns: &[String], rows: &[Vec<Value>]) -> String {
    let mut output = String::new();

    // Header comment
    output.push_str(&format!("-- Export of table: {}\n", table_name));
    output.push_str(&format!("-- Rows: {}\n", rows.len()));
    output.push_str("-- Generated by D1 Manager\n\n");

    if rows.is_empty() {
        output.push_str("-- No data to export\n");
        return output;
    }

    // Generate INSERT statements
    let columns_str = columns.iter()
        .map(|c| format!("\"{}\"", c))
        .collect::<Vec<_>>()
        .join(", ");

    for row in rows {
        let values: Vec<String> = row.iter()
            .map(|v| value_to_sql(v))
            .collect();

        output.push_str(&format!(
            "INSERT INTO \"{}\" ({}) VALUES ({});\n",
            table_name,
            columns_str,
            values.join(", ")
        ));
    }

    output
}

/// Export full database schema and data (SQL dump)
pub fn export_database_dump(
    tables: &[(String, Vec<String>, Vec<Vec<Value>>)],
    schema_sql: &[(String, String)], // (table_name, create_statement)
) -> String {
    let mut output = String::new();

    output.push_str("-- D1 Database Dump\n");
    output.push_str("-- Generated by D1 Manager\n");
    output.push_str(&format!("-- Date: {}\n\n", chrono_now()));
    output.push_str("PRAGMA foreign_keys=OFF;\n");
    output.push_str("BEGIN TRANSACTION;\n\n");

    // Schema (CREATE TABLE statements)
    for (table_name, create_sql) in schema_sql {
        output.push_str(&format!("-- Table: {}\n", table_name));
        output.push_str(create_sql);
        if !create_sql.ends_with(';') {
            output.push(';');
        }
        output.push_str("\n\n");
    }

    // Data
    for (table_name, columns, rows) in tables {
        if !rows.is_empty() {
            output.push_str(&format!("-- Data for table: {}\n", table_name));
            output.push_str(&export_to_sql(table_name, columns, rows));
            output.push('\n');
        }
    }

    output.push_str("COMMIT;\n");
    output.push_str("PRAGMA foreign_keys=ON;\n");

    output
}

/// Escape a field for CSV format
fn escape_csv_field(field: &str) -> String {
    if field.contains(',') || field.contains('"') || field.contains('\n') || field.contains('\r') {
        format!("\"{}\"", field.replace('"', "\"\""))
    } else {
        field.to_string()
    }
}

/// Convert JSON value to string for display
fn value_to_string(value: &Value) -> String {
    match value {
        Value::Null => String::new(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => s.clone(),
        Value::Array(arr) => serde_json::to_string(arr).unwrap_or_default(),
        Value::Object(obj) => serde_json::to_string(obj).unwrap_or_default(),
    }
}

/// Convert JSON value to SQL literal
fn value_to_sql(value: &Value) -> String {
    match value {
        Value::Null => "NULL".to_string(),
        Value::Bool(b) => if *b { "1" } else { "0" }.to_string(),
        Value::Number(n) => n.to_string(),
        Value::String(s) => format!("'{}'", s.replace('\'', "''")),
        Value::Array(arr) => format!("'{}'", serde_json::to_string(arr).unwrap_or_default().replace('\'', "''")),
        Value::Object(obj) => format!("'{}'", serde_json::to_string(obj).unwrap_or_default().replace('\'', "''")),
    }
}

/// Get current timestamp as string
fn chrono_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // Simple ISO-like format without external crate
    let days = secs / 86400;
    let years = 1970 + days / 365;
    format!("{}-XX-XX", years)
}

/// Save content to file using file dialog
pub fn save_to_file(content: &str, default_name: &str, extension: &str) -> Result<std::path::PathBuf, String> {
    let file_path = rfd::FileDialog::new()
        .set_file_name(&format!("{}.{}", default_name, extension))
        .add_filter(extension.to_uppercase(), &[extension])
        .add_filter("All Files", &["*"])
        .save_file()
        .ok_or_else(|| "Export cancelled".to_string())?;

    let mut file = std::fs::File::create(&file_path)
        .map_err(|e| format!("Failed to create file: {}", e))?;

    file.write_all(content.as_bytes())
        .map_err(|e| format!("Failed to write file: {}", e))?;

    Ok(file_path)
}

// ============================================
// Import Functions
// ============================================

/// Result of parsing an import file
#[derive(Debug, Clone)]
pub struct ImportData {
    pub columns: Vec<String>,
    pub rows: Vec<Vec<Value>>,
}

/// Open file picker and read content
pub fn pick_and_read_file(format: ImportFormat) -> Result<(String, String), String> {
    let extensions: &[&str] = match format {
        ImportFormat::Csv => &["csv", "txt"],
        ImportFormat::Json => &["json"],
        ImportFormat::Sql => &["sql"],
        ImportFormat::MySqlDump => &["sql", "dump"],
    };

    let file_path = rfd::FileDialog::new()
        .add_filter(format.extension().to_uppercase(), extensions)
        .add_filter("All Files", &["*"])
        .pick_file()
        .ok_or_else(|| "Import cancelled".to_string())?;

    let content = std::fs::read_to_string(&file_path)
        .map_err(|e| format!("Failed to read file: {}", e))?;

    let filename = file_path
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("unknown")
        .to_string();

    Ok((content, filename))
}

/// Parse CSV content into columns and rows
pub fn parse_csv(content: &str) -> Result<ImportData, String> {
    let mut lines = content.lines().peekable();

    // Parse header
    let header_line = lines.next().ok_or("CSV file is empty")?;
    let columns: Vec<String> = parse_csv_line(header_line);

    if columns.is_empty() {
        return Err("No columns found in CSV header".to_string());
    }

    // Parse data rows
    let mut rows = Vec::new();
    for line in lines {
        if line.trim().is_empty() {
            continue;
        }

        let values = parse_csv_line(line);
        let row: Vec<Value> = values
            .into_iter()
            .map(|s| {
                if s.is_empty() {
                    Value::Null
                } else if let Ok(n) = s.parse::<i64>() {
                    Value::Number(n.into())
                } else if let Ok(n) = s.parse::<f64>() {
                    Value::Number(serde_json::Number::from_f64(n).unwrap_or_else(|| 0.into()))
                } else if s.eq_ignore_ascii_case("true") {
                    Value::Bool(true)
                } else if s.eq_ignore_ascii_case("false") {
                    Value::Bool(false)
                } else if s.eq_ignore_ascii_case("null") {
                    Value::Null
                } else {
                    Value::String(s)
                }
            })
            .collect();

        // Pad with nulls if row is shorter than header
        let mut padded_row = row;
        while padded_row.len() < columns.len() {
            padded_row.push(Value::Null);
        }

        rows.push(padded_row);
    }

    Ok(ImportData { columns, rows })
}

/// Parse a single CSV line handling quoted fields
fn parse_csv_line(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();

    while let Some(c) = chars.next() {
        if in_quotes {
            if c == '"' {
                if chars.peek() == Some(&'"') {
                    // Escaped quote
                    current.push('"');
                    chars.next();
                } else {
                    // End of quoted field
                    in_quotes = false;
                }
            } else {
                current.push(c);
            }
        } else {
            match c {
                '"' => in_quotes = true,
                ',' => {
                    fields.push(current.trim().to_string());
                    current = String::new();
                }
                _ => current.push(c),
            }
        }
    }

    fields.push(current.trim().to_string());
    fields
}

/// Parse JSON content into columns and rows
pub fn parse_json(content: &str) -> Result<ImportData, String> {
    let data: Vec<serde_json::Map<String, Value>> = serde_json::from_str(content)
        .map_err(|e| format!("Invalid JSON: {}", e))?;

    if data.is_empty() {
        return Err("JSON array is empty".to_string());
    }

    // Collect all unique column names from all objects
    let mut column_set = std::collections::HashSet::new();
    for obj in &data {
        for key in obj.keys() {
            column_set.insert(key.clone());
        }
    }

    let columns: Vec<String> = column_set.into_iter().collect();

    // Build rows
    let rows: Vec<Vec<Value>> = data
        .iter()
        .map(|obj| {
            columns
                .iter()
                .map(|col| obj.get(col).cloned().unwrap_or(Value::Null))
                .collect()
        })
        .collect();

    Ok(ImportData { columns, rows })
}

/// Parse SQL file and extract statements
pub fn parse_sql(content: &str) -> Result<Vec<String>, String> {
    let mut statements = Vec::new();
    let mut current = String::new();
    let mut in_string = false;
    let mut string_char = ' ';

    for c in content.chars() {
        if in_string {
            current.push(c);
            if c == string_char {
                in_string = false;
            }
        } else {
            match c {
                '\'' | '"' => {
                    in_string = true;
                    string_char = c;
                    current.push(c);
                }
                ';' => {
                    let stmt = current.trim().to_string();
                    if !stmt.is_empty() && !stmt.starts_with("--") {
                        statements.push(stmt);
                    }
                    current = String::new();
                }
                '-' if current.ends_with('-') => {
                    // Skip single-line comments
                    current.pop();
                    // Skip until newline
                }
                '\n' => {
                    if !current.trim().starts_with("--") {
                        current.push(' ');
                    } else {
                        current = String::new();
                    }
                }
                _ => current.push(c),
            }
        }
    }

    // Handle final statement without semicolon
    let final_stmt = current.trim().to_string();
    if !final_stmt.is_empty() && !final_stmt.starts_with("--") {
        statements.push(final_stmt);
    }

    if statements.is_empty() {
        return Err("No SQL statements found".to_string());
    }

    Ok(statements)
}

/// Generate INSERT statements from import data
pub fn generate_insert_statements(
    table_name: &str,
    data: &ImportData,
    strategy: ConflictStrategy,
) -> Vec<String> {
    let columns_str = data.columns
        .iter()
        .map(|c| format!("\"{}\"", c))
        .collect::<Vec<_>>()
        .join(", ");

    let insert_keyword = strategy.sql_keyword();

    data.rows
        .iter()
        .map(|row| {
            let values: Vec<String> = row.iter().map(value_to_sql).collect();
            format!(
                "{} \"{}\" ({}) VALUES ({});",
                insert_keyword,
                table_name,
                columns_str,
                values.join(", ")
            )
        })
        .collect()
}

// ============================================
// MySQL Dump Conversion
// ============================================

/// Result of parsing MySQL dump
#[derive(Debug, Clone)]
pub struct MySqlConversionResult {
    pub statements: Vec<String>,
    pub warnings: Vec<String>,
    pub tables_found: Vec<String>,
    pub insert_count: usize,
}

/// Parse and convert MySQL dump to SQLite-compatible statements
pub fn parse_mysql_dump(content: &str) -> Result<MySqlConversionResult, String> {
    let mut statements = Vec::new();
    let mut warnings = Vec::new();
    let mut tables_found = Vec::new();
    let mut insert_count = 0;

    // Split into individual statements
    let raw_statements = split_sql_statements(content);

    for stmt in raw_statements {
        let stmt = stmt.trim();
        if stmt.is_empty() {
            continue;
        }

        let upper = stmt.to_uppercase();

        // Skip MySQL-specific commands that SQLite doesn't support
        if upper.starts_with("SET ")
            || upper.starts_with("/*!") && upper.contains("*/")
            || upper.starts_with("LOCK TABLES")
            || upper.starts_with("UNLOCK TABLES")
            || upper.starts_with("START TRANSACTION")
            || upper.starts_with("COMMIT")
            || upper.starts_with("ROLLBACK")
            || upper.starts_with("USE ")
            || upper.starts_with("DROP DATABASE")
            || upper.starts_with("CREATE DATABASE")
            || upper.starts_with("ALTER DATABASE")
        {
            continue;
        }

        // Handle CREATE TABLE
        if upper.starts_with("CREATE TABLE") {
            match convert_create_table(stmt) {
                Ok((converted, table_name)) => {
                    tables_found.push(table_name);
                    statements.push(converted);
                }
                Err(e) => {
                    warnings.push(format!("Skipped CREATE TABLE: {}", e));
                }
            }
            continue;
        }

        // Handle DROP TABLE (convert to DROP TABLE IF EXISTS)
        if upper.starts_with("DROP TABLE") {
            let converted = convert_drop_table(stmt);
            statements.push(converted);
            continue;
        }

        // Handle INSERT statements
        if upper.starts_with("INSERT") {
            match convert_insert(stmt) {
                Ok(converted) => {
                    insert_count += 1;
                    statements.push(converted);
                }
                Err(e) => {
                    warnings.push(format!("Skipped INSERT: {}", e));
                }
            }
            continue;
        }

        // Handle CREATE INDEX
        if upper.starts_with("CREATE INDEX") || upper.starts_with("CREATE UNIQUE INDEX") {
            match convert_create_index(stmt) {
                Ok(converted) => {
                    statements.push(converted);
                }
                Err(e) => {
                    warnings.push(format!("Skipped INDEX: {}", e));
                }
            }
            continue;
        }

        // Skip other unsupported statements
        if upper.starts_with("ALTER TABLE")
            || upper.starts_with("CREATE TRIGGER")
            || upper.starts_with("CREATE VIEW")
            || upper.starts_with("CREATE PROCEDURE")
            || upper.starts_with("CREATE FUNCTION")
        {
            warnings.push(format!("Skipped unsupported: {}", &stmt[..stmt.len().min(50)]));
            continue;
        }
    }

    if statements.is_empty() {
        return Err("No convertible SQL statements found in MySQL dump".to_string());
    }

    Ok(MySqlConversionResult {
        statements,
        warnings,
        tables_found,
        insert_count,
    })
}

/// Split SQL content into individual statements, handling string literals
fn split_sql_statements(content: &str) -> Vec<String> {
    let mut statements = Vec::new();
    let mut current = String::new();
    let mut in_string = false;
    let mut string_char = ' ';
    let mut in_comment = false;
    let mut prev_char = ' ';

    for c in content.chars() {
        // Handle multi-line comments
        if !in_string && prev_char == '/' && c == '*' {
            in_comment = true;
            current.pop(); // Remove the '/'
            prev_char = c;
            continue;
        }
        if in_comment {
            if prev_char == '*' && c == '/' {
                in_comment = false;
            }
            prev_char = c;
            continue;
        }

        // Handle single-line comments
        if !in_string && prev_char == '-' && c == '-' {
            current.pop(); // Remove the first '-'
            // Skip until newline
            prev_char = c;
            continue;
        }

        if in_string {
            current.push(c);
            // Handle escaped quotes
            if c == string_char && prev_char != '\\' {
                in_string = false;
            }
        } else {
            match c {
                '\'' | '"' | '`' => {
                    in_string = true;
                    string_char = c;
                    current.push(c);
                }
                ';' => {
                    let stmt = current.trim().to_string();
                    if !stmt.is_empty() {
                        statements.push(stmt);
                    }
                    current = String::new();
                }
                '\n' | '\r' => {
                    current.push(' ');
                }
                _ => current.push(c),
            }
        }
        prev_char = c;
    }

    // Handle final statement without semicolon
    let final_stmt = current.trim().to_string();
    if !final_stmt.is_empty() {
        statements.push(final_stmt);
    }

    statements
}

/// Convert MySQL CREATE TABLE to SQLite
fn convert_create_table(stmt: &str) -> Result<(String, String), String> {
    // Extract table name
    let re_table = regex_lite::Regex::new(r"(?i)CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`'\x22]?(\w+)[`'\x22]?")
        .map_err(|e| e.to_string())?;

    let table_name = re_table
        .captures(stmt)
        .and_then(|c| c.get(1))
        .map(|m| m.as_str().to_string())
        .ok_or("Could not extract table name")?;

    // Find the column definitions section (between first ( and last ))
    let start_paren = stmt.find('(').ok_or("No opening parenthesis found")?;
    let end_paren = stmt.rfind(')').ok_or("No closing parenthesis found")?;

    if start_paren >= end_paren {
        return Err("Invalid CREATE TABLE structure".to_string());
    }

    let columns_section = &stmt[start_paren + 1..end_paren];
    let converted_columns = convert_column_definitions(columns_section)?;

    let result = format!(
        "CREATE TABLE IF NOT EXISTS \"{}\" (\n{}\n)",
        table_name,
        converted_columns
    );

    Ok((result, table_name))
}

/// Convert MySQL column definitions to SQLite
fn convert_column_definitions(columns_section: &str) -> Result<String, String> {
    let mut result_columns = Vec::new();
    let mut primary_keys = Vec::new();
    let mut unique_constraints = Vec::new();

    // Split by comma, but handle nested parentheses
    let column_defs = split_column_definitions(columns_section);

    for col_def in column_defs {
        let col_def = col_def.trim();
        if col_def.is_empty() {
            continue;
        }

        let upper = col_def.to_uppercase();

        // Handle PRIMARY KEY constraint
        if upper.starts_with("PRIMARY KEY") {
            if let Some(keys) = extract_key_columns(col_def) {
                primary_keys.extend(keys);
            }
            continue;
        }

        // Handle UNIQUE constraint
        if upper.starts_with("UNIQUE KEY") || upper.starts_with("UNIQUE INDEX") || upper.starts_with("UNIQUE (") {
            if let Some(keys) = extract_key_columns(col_def) {
                unique_constraints.push(keys);
            }
            continue;
        }

        // Handle KEY/INDEX (skip for SQLite - handle separately)
        if upper.starts_with("KEY ") || upper.starts_with("INDEX ") {
            continue;
        }

        // Handle FOREIGN KEY (simplified - skip complex constraints)
        if upper.starts_with("FOREIGN KEY") || upper.starts_with("CONSTRAINT") {
            continue;
        }

        // Handle FULLTEXT, SPATIAL indexes (not supported in SQLite)
        if upper.starts_with("FULLTEXT") || upper.starts_with("SPATIAL") {
            continue;
        }

        // Regular column definition
        if let Some(converted) = convert_single_column(col_def) {
            result_columns.push(converted);
        }
    }

    // Add primary key constraint if needed
    if !primary_keys.is_empty() && primary_keys.len() > 1 {
        result_columns.push(format!(
            "  PRIMARY KEY ({})",
            primary_keys.iter().map(|k| format!("\"{}\"", k)).collect::<Vec<_>>().join(", ")
        ));
    }

    // Add unique constraints
    for keys in unique_constraints {
        if keys.len() == 1 {
            // Single column unique - should be in column definition
            continue;
        }
        result_columns.push(format!(
            "  UNIQUE ({})",
            keys.iter().map(|k| format!("\"{}\"", k)).collect::<Vec<_>>().join(", ")
        ));
    }

    Ok(result_columns.join(",\n"))
}

/// Split column definitions handling nested parentheses
fn split_column_definitions(section: &str) -> Vec<String> {
    let mut result = Vec::new();
    let mut current = String::new();
    let mut paren_depth = 0;
    let mut in_string = false;
    let mut string_char = ' ';

    for c in section.chars() {
        if in_string {
            current.push(c);
            if c == string_char {
                in_string = false;
            }
            continue;
        }

        match c {
            '\'' | '"' | '`' => {
                in_string = true;
                string_char = c;
                current.push(c);
            }
            '(' => {
                paren_depth += 1;
                current.push(c);
            }
            ')' => {
                paren_depth -= 1;
                current.push(c);
            }
            ',' if paren_depth == 0 => {
                result.push(current.trim().to_string());
                current = String::new();
            }
            _ => current.push(c),
        }
    }

    if !current.trim().is_empty() {
        result.push(current.trim().to_string());
    }

    result
}

/// Convert a single column definition from MySQL to SQLite
fn convert_single_column(col_def: &str) -> Option<String> {
    let parts: Vec<&str> = col_def.split_whitespace().collect();
    if parts.is_empty() {
        return None;
    }

    // Extract column name (remove backticks/quotes)
    let col_name = parts[0].trim_matches(|c| c == '`' || c == '\'' || c == '"');

    if parts.len() < 2 {
        return Some(format!("  \"{}\" TEXT", col_name));
    }

    // Extract and convert data type
    let mut idx = 1;
    let data_type_raw = parts[idx];
    let sqlite_type = convert_mysql_type(data_type_raw);
    idx += 1;

    // Handle type with size specification like VARCHAR(255)
    if data_type_raw.contains('(') {
        // Type already includes size, continue
    } else if idx < parts.len() && parts[idx].starts_with('(') {
        // Skip size specification
        while idx < parts.len() && !parts[idx].contains(')') {
            idx += 1;
        }
        if idx < parts.len() {
            idx += 1;
        }
    }

    // Build column definition
    let mut result = format!("  \"{}\" {}", col_name, sqlite_type);

    // Process remaining parts for constraints
    let remaining = parts[idx..].join(" ").to_uppercase();

    if remaining.contains("NOT NULL") {
        result.push_str(" NOT NULL");
    }

    if remaining.contains("PRIMARY KEY") {
        result.push_str(" PRIMARY KEY");
    }

    if remaining.contains("AUTOINCREMENT") || remaining.contains("AUTO_INCREMENT") {
        // SQLite uses INTEGER PRIMARY KEY for auto-increment
        if !result.contains("PRIMARY KEY") {
            result = result.replace(&sqlite_type, "INTEGER PRIMARY KEY");
        }
    }

    if remaining.contains("UNIQUE") && !remaining.contains("UNIQUE KEY") {
        result.push_str(" UNIQUE");
    }

    // Handle DEFAULT
    if let Some(default_pos) = remaining.find("DEFAULT") {
        let after_default = &remaining[default_pos + 7..].trim_start();
        if let Some(default_value) = extract_default_value(after_default) {
            result.push_str(&format!(" DEFAULT {}", default_value));
        }
    }

    Some(result)
}

/// Extract default value from remaining string
fn extract_default_value(s: &str) -> Option<String> {
    let s = s.trim();
    if s.is_empty() {
        return None;
    }

    // Handle quoted strings
    if s.starts_with('\'') {
        if let Some(end) = s[1..].find('\'') {
            return Some(format!("'{}'", &s[1..end + 1]));
        }
    }

    // Handle NULL
    if s.starts_with("NULL") {
        return Some("NULL".to_string());
    }

    // Handle numbers
    let word: String = s.chars().take_while(|c| c.is_alphanumeric() || *c == '.' || *c == '-').collect();
    if !word.is_empty() {
        if word.parse::<f64>().is_ok() || word.to_uppercase() == "TRUE" || word.to_uppercase() == "FALSE" {
            return Some(word);
        }
    }

    None
}

/// Convert MySQL data type to SQLite type
fn convert_mysql_type(mysql_type: &str) -> &'static str {
    let upper = mysql_type.to_uppercase();
    let base_type = upper.split('(').next().unwrap_or(&upper);

    match base_type {
        // Integer types
        "TINYINT" | "SMALLINT" | "MEDIUMINT" | "INT" | "INTEGER" | "BIGINT" => "INTEGER",
        "BOOL" | "BOOLEAN" => "INTEGER",

        // Floating point
        "FLOAT" | "DOUBLE" | "DECIMAL" | "NUMERIC" | "REAL" => "REAL",

        // Text types
        "CHAR" | "VARCHAR" | "TINYTEXT" | "TEXT" | "MEDIUMTEXT" | "LONGTEXT" => "TEXT",
        "ENUM" | "SET" => "TEXT",

        // Binary types
        "BINARY" | "VARBINARY" | "TINYBLOB" | "BLOB" | "MEDIUMBLOB" | "LONGBLOB" => "BLOB",

        // Date/time types - store as TEXT in SQLite
        "DATE" | "TIME" | "DATETIME" | "TIMESTAMP" | "YEAR" => "TEXT",

        // JSON - store as TEXT
        "JSON" => "TEXT",

        // Default
        _ => "TEXT",
    }
}

/// Extract column names from KEY definition
fn extract_key_columns(key_def: &str) -> Option<Vec<String>> {
    let start = key_def.find('(')?;
    let end = key_def.rfind(')')?;

    if start >= end {
        return None;
    }

    let columns_str = &key_def[start + 1..end];
    let columns: Vec<String> = columns_str
        .split(',')
        .map(|s| {
            let s = s.trim();
            // Remove backticks and any size specification like (255)
            let name = s.split('(').next().unwrap_or(s);
            name.trim_matches(|c| c == '`' || c == '\'' || c == '"').to_string()
        })
        .filter(|s| !s.is_empty())
        .collect();

    if columns.is_empty() {
        None
    } else {
        Some(columns)
    }
}

/// Convert DROP TABLE statement
fn convert_drop_table(stmt: &str) -> String {
    let re = regex_lite::Regex::new(r"(?i)DROP\s+TABLE\s+(?:IF\s+EXISTS\s+)?[`'\x22]?(\w+)")
        .ok();

    if let Some(re) = re {
        if let Some(caps) = re.captures(stmt) {
            if let Some(table_name) = caps.get(1) {
                return format!("DROP TABLE IF EXISTS \"{}\"", table_name.as_str());
            }
        }
    }

    // Fallback: just make it IF EXISTS
    stmt.replace("DROP TABLE ", "DROP TABLE IF EXISTS ")
}

/// Convert INSERT statement (handle backticks, etc.)
fn convert_insert(stmt: &str) -> Result<String, String> {
    // Replace backticks with double quotes for identifiers
    let converted = stmt
        .replace('`', "\"")
        // Handle MySQL's INSERT IGNORE
        .replace("INSERT IGNORE", "INSERT OR IGNORE");

    Ok(converted)
}

/// Convert CREATE INDEX statement
fn convert_create_index(stmt: &str) -> Result<String, String> {
    // Replace backticks with double quotes
    let converted = stmt.replace('`', "\"");
    Ok(converted)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_csv_export() {
        let columns = vec!["id".to_string(), "name".to_string()];
        let rows = vec![
            vec![Value::Number(1.into()), Value::String("Alice".to_string())],
            vec![Value::Number(2.into()), Value::String("Bob".to_string())],
        ];

        let csv = export_to_csv(&columns, &rows);
        assert!(csv.contains("id,name"));
        assert!(csv.contains("1,Alice"));
    }

    #[test]
    fn test_csv_escape() {
        assert_eq!(escape_csv_field("hello"), "hello");
        assert_eq!(escape_csv_field("hello,world"), "\"hello,world\"");
        assert_eq!(escape_csv_field("hello\"world"), "\"hello\"\"world\"");
    }

    #[test]
    fn test_sql_escape() {
        assert_eq!(value_to_sql(&Value::String("test".to_string())), "'test'");
        assert_eq!(value_to_sql(&Value::String("it's".to_string())), "'it''s'");
        assert_eq!(value_to_sql(&Value::Null), "NULL");
    }

    #[test]
    fn test_mysql_type_conversion() {
        assert_eq!(convert_mysql_type("VARCHAR(255)"), "TEXT");
        assert_eq!(convert_mysql_type("INT"), "INTEGER");
        assert_eq!(convert_mysql_type("BIGINT"), "INTEGER");
        assert_eq!(convert_mysql_type("DECIMAL(10,2)"), "REAL");
        assert_eq!(convert_mysql_type("DATETIME"), "TEXT");
        assert_eq!(convert_mysql_type("BLOB"), "BLOB");
    }

    #[test]
    fn test_mysql_create_table() {
        let mysql = "CREATE TABLE `users` (
            `id` INT AUTO_INCREMENT PRIMARY KEY,
            `name` VARCHAR(255) NOT NULL,
            `email` VARCHAR(255) UNIQUE
        )";

        let result = convert_create_table(mysql);
        assert!(result.is_ok());
        let (sql, table) = result.unwrap();
        assert_eq!(table, "users");
        assert!(sql.contains("\"users\""));
        assert!(sql.contains("INTEGER"));
    }
}
